# Tests for the sourced-file shell env scheme (item #6).
#
# aictl writes env vars to ~/.config/aictl/env.sh and appends only a
# bounded source-line block to shell profiles. This file verifies:
#   - env.sh is (re)generated with the expected exports
#   - profiles only get the 3-line marker block (no raw exports)
#   - the block is idempotent on re-run
#   - legacy in-profile blocks are migrated away
#   - both bash and zsh profiles receive the source block when present

from __future__ import annotations

from pathlib import Path

import pytest
from click.testing import CliRunner

from aictl.commands.integrations import _AICTL_ENV_BEGIN, _AICTL_ENV_END, otel


@pytest.fixture
def fake_home(tmp_path, monkeypatch):
    monkeypatch.setenv("HOME", str(tmp_path))
    monkeypatch.setenv("AICTL_PORT", "8484")
    monkeypatch.setattr("aictl.commands.integrations.claude_global_dir", lambda: tmp_path / "claude")
    monkeypatch.setattr("aictl.commands.integrations.vscode_user_dir", lambda: tmp_path / "vscode")
    monkeypatch.setattr("aictl.commands.integrations.codex_global_dir", lambda: tmp_path / "codex")
    monkeypatch.setattr("aictl.commands.integrations.gemini_global_dir", lambda: tmp_path / "gemini")
    return tmp_path


def _env_file(home: Path) -> Path:
    return home / ".config" / "aictl" / "env.sh"


class TestEnvFileWritten:
    def test_otel_enable_creates_env_file(self, fake_home, monkeypatch):
        profile = fake_home / ".zshrc"
        profile.write_text("")
        monkeypatch.setattr("aictl.commands.integrations._shell_profiles", lambda: [profile])
        runner = CliRunner()
        result = runner.invoke(otel, ["enable", "--tool", "claude"], catch_exceptions=False)
        assert result.exit_code == 0
        env_file = _env_file(fake_home)
        assert env_file.exists()
        content = env_file.read_text(encoding="utf-8")
        assert 'export AICTL_PORT="8484"' in content
        assert "generated by aictl, do not edit" in content

    def test_profile_only_contains_source_line(self, fake_home, monkeypatch):
        profile = fake_home / ".zshrc"
        profile.write_text("# original user content\n")
        monkeypatch.setattr("aictl.commands.integrations._shell_profiles", lambda: [profile])
        runner = CliRunner()
        runner.invoke(otel, ["enable", "--tool", "claude"], catch_exceptions=False)
        content = profile.read_text(encoding="utf-8")
        assert "# original user content" in content
        assert _AICTL_ENV_BEGIN in content
        assert _AICTL_ENV_END in content
        # Profile must NOT contain raw exports — they live in env.sh
        assert "export AICTL_PORT" not in content
        assert "export OTEL_EXPORTER_OTLP_ENDPOINT" not in content

    def test_idempotent_on_rerun(self, fake_home, monkeypatch):
        profile = fake_home / ".zshrc"
        profile.write_text("")
        monkeypatch.setattr("aictl.commands.integrations._shell_profiles", lambda: [profile])
        runner = CliRunner()
        runner.invoke(otel, ["enable", "--tool", "claude"], catch_exceptions=False)
        first = profile.read_text(encoding="utf-8")
        runner.invoke(otel, ["enable", "--tool", "claude"], catch_exceptions=False)
        second = profile.read_text(encoding="utf-8")
        assert first == second
        # Block should appear exactly once
        assert second.count(_AICTL_ENV_BEGIN) == 1

    def test_env_file_regenerated_on_rerun(self, fake_home, monkeypatch):
        """Changing the set of tools regenerates env.sh (no stale keys)."""
        profile = fake_home / ".zshrc"
        profile.write_text("")
        monkeypatch.setattr("aictl.commands.integrations._shell_profiles", lambda: [profile])
        runner = CliRunner()
        runner.invoke(otel, ["enable", "--tool", "gemini"], catch_exceptions=False)
        first = _env_file(fake_home).read_text(encoding="utf-8")
        assert "GEMINI_OTEL_ENABLED" in first

        runner.invoke(otel, ["enable", "--tool", "claude"], catch_exceptions=False)
        second = _env_file(fake_home).read_text(encoding="utf-8")
        # Claude-only run must not carry forward Gemini-specific keys
        assert "GEMINI_OTEL_ENABLED" not in second

    def test_writes_to_both_bashrc_and_zshrc_when_present(self, fake_home, monkeypatch):
        bashrc = fake_home / ".bashrc"
        zshrc = fake_home / ".zshrc"
        bashrc.write_text("")
        zshrc.write_text("")
        # Use the real _shell_profiles with HOME redirected
        runner = CliRunner()
        result = runner.invoke(otel, ["enable", "--tool", "claude"], catch_exceptions=False)
        assert result.exit_code == 0
        assert _AICTL_ENV_BEGIN in bashrc.read_text(encoding="utf-8")
        assert _AICTL_ENV_BEGIN in zshrc.read_text(encoding="utf-8")


class TestLegacyBlockMigration:
    def test_legacy_inline_block_is_stripped(self, fake_home, monkeypatch):
        """An old _OTEL_MARKER block with inline exports is removed on next enable."""
        legacy_marker = "# \u2500\u2500 aictl: OTel for AI tools \u2500\u2500"
        profile = fake_home / ".zshrc"
        profile.write_text(
            "# user content above\n"
            f"{legacy_marker}\n"
            "export AICTL_PORT=8484\n"
            'export OTEL_EXPORTER_OTLP_ENDPOINT="http://localhost:8484"\n'
            "# user content below\n",
            encoding="utf-8",
        )
        monkeypatch.setattr("aictl.commands.integrations._shell_profiles", lambda: [profile])

        runner = CliRunner()
        runner.invoke(otel, ["enable", "--tool", "claude"], catch_exceptions=False)
        content = profile.read_text(encoding="utf-8")
        # Legacy marker and inline exports are gone
        assert legacy_marker not in content
        assert "export AICTL_PORT=8484" not in content
        assert 'export OTEL_EXPORTER_OTLP_ENDPOINT="http://localhost:8484"' not in content
        # Surrounding user content is preserved
        assert "user content above" in content
        assert "user content below" in content
        # New source-line block is present
        assert _AICTL_ENV_BEGIN in content


class TestCorruptEnvFileOverwrite:
    def test_atomic_replace_never_leaves_partial(self, fake_home, monkeypatch):
        """env.sh is written via temp + os.replace — tmp file must not linger."""
        profile = fake_home / ".zshrc"
        profile.write_text("")
        monkeypatch.setattr("aictl.commands.integrations._shell_profiles", lambda: [profile])
        runner = CliRunner()
        runner.invoke(otel, ["enable", "--tool", "claude"], catch_exceptions=False)
        env_dir = _env_file(fake_home).parent
        tmp_files = list(env_dir.glob("*.tmp"))
        assert tmp_files == []


class TestUninstallRemoval:
    """The enable marker-block machinery is reversible by removing env.sh + block."""

    def test_removing_env_file_and_block_disables_cleanly(self, fake_home, monkeypatch):
        profile = fake_home / ".zshrc"
        profile.write_text("")
        monkeypatch.setattr("aictl.commands.integrations._shell_profiles", lambda: [profile])
        runner = CliRunner()
        runner.invoke(otel, ["enable", "--tool", "claude"], catch_exceptions=False)

        env_file = _env_file(fake_home)
        assert env_file.exists()
        # Simulate a clean uninstall: wipe env.sh + the marker block
        env_file.unlink()
        content = profile.read_text(encoding="utf-8")
        lines = content.splitlines()
        out = []
        skipping = False
        for line in lines:
            if _AICTL_ENV_BEGIN in line:
                skipping = True
                continue
            if _AICTL_ENV_END in line:
                skipping = False
                continue
            if not skipping:
                out.append(line)
        profile.write_text("\n".join(out) + "\n", encoding="utf-8")
        # Profile is back to its original empty state (plus a trailing newline)
        assert _AICTL_ENV_BEGIN not in profile.read_text(encoding="utf-8")
        assert not env_file.exists()


class TestEnableVerifyRoundtrip:
    """Regression: enable and verify must agree on the marker string.

    Catches the original bug where enable wrote ``# >>> aictl env >>>`` but
    verify still looked for the legacy ``# ── aictl: OTel for AI tools ──``
    marker, causing every freshly-enabled profile to be reported MISSING.
    """

    def test_verify_recognises_marker_written_by_enable(self, fake_home, monkeypatch):
        bashrc = fake_home / ".bashrc"
        zshrc = fake_home / ".zshrc"
        bashrc.write_text("")
        zshrc.write_text("")
        runner = CliRunner()
        enable_result = runner.invoke(
            otel, ["enable", "--tool", "claude"], catch_exceptions=False
        )
        assert enable_result.exit_code == 0
        # Sanity: enable wrote the new-scheme marker into each profile.
        assert _AICTL_ENV_BEGIN in bashrc.read_text(encoding="utf-8")
        assert _AICTL_ENV_BEGIN in zshrc.read_text(encoding="utf-8")

        # Verify must report OK for every profile enable just wrote — not MISSING.
        verify_result = runner.invoke(otel, ["verify"], catch_exceptions=False)
        assert verify_result.exit_code == 0
        out = verify_result.output
        # Find the Shell profiles section
        shell_section_start = out.index("Shell profiles:")
        # Cut at the next blank-line section break, or end of output
        section_end_candidates = [
            out.index(hdr, shell_section_start)
            for hdr in ("VS Code settings:", "Codex config:", "aictl server:")
            if hdr in out[shell_section_start:]
        ]
        shell_section_end = min(section_end_candidates) if section_end_candidates else len(out)
        shell_section = out[shell_section_start:shell_section_end]
        assert "MISSING" not in shell_section, (
            "verify reported MISSING for a profile enable just wrote:\n" + shell_section
        )
        # Both profiles should be listed as OK
        assert str(bashrc) in shell_section
        assert str(zshrc) in shell_section



class TestAgentWorkspaceProfile:
    """agent-workspace producer: AW_OTLP_ENDPOINT + AW_CONTEXT_PROFILE (config↔action)."""

    def test_enable_agent_workspace_writes_aw_endpoint_and_profile(self, fake_home, monkeypatch):
        profile_rc = fake_home / ".zshrc"
        profile_rc.write_text("")
        monkeypatch.setattr("aictl.commands.integrations._shell_profiles", lambda: [profile_rc])
        runner = CliRunner()
        result = runner.invoke(
            otel,
            ["enable", "--tool", "agent-workspace", "--profile", "review"],
            catch_exceptions=False,
        )
        assert result.exit_code == 0
        content = _env_file(fake_home).read_text(encoding="utf-8")
        assert 'export AW_OTLP_ENDPOINT="http://localhost:8484"' in content
        assert 'export AW_CONTEXT_PROFILE="review"' in content

    def test_default_all_includes_agent_workspace_endpoint(self, fake_home, monkeypatch):
        profile_rc = fake_home / ".zshrc"
        profile_rc.write_text("")
        monkeypatch.setattr("aictl.commands.integrations._shell_profiles", lambda: [profile_rc])
        runner = CliRunner()
        result = runner.invoke(otel, ["enable"], catch_exceptions=False)  # --tool all (default)
        assert result.exit_code == 0
        content = _env_file(fake_home).read_text(encoding="utf-8")
        assert "AW_OTLP_ENDPOINT" in content  # workspace export on by default
        assert "AW_CONTEXT_PROFILE" not in content  # but no profile unless asked

    def test_print_emits_aw_vars_for_eval(self):
        runner = CliRunner()
        result = runner.invoke(
            otel,
            ["enable", "--print", "--tool", "agent-workspace", "--profile", "review", "--shell", "bash"],
            catch_exceptions=False,
        )
        assert result.exit_code == 0
        assert 'export AW_OTLP_ENDPOINT="http://localhost:8484"' in result.output
        assert 'export AW_CONTEXT_PROFILE="review"' in result.output
