import { html } from 'htm/preact';
// Tree-shakeable named imports — only the icons referenced here end up in the bundle.
// Add new names as components start using them.
import {
  Activity,
  AlertTriangle,
  Archive,
  Banknote,
  BarChart3,
  BookOpen,
  Bot,
  Brain,
  BrainCircuit,
  ChevronDown,
  ChevronRight,
  ClipboardList,
  Clock,
  Coins,
  Cpu,
  FilePen,
  FileText,
  GitBranch,
  Globe,
  Grid3x3,
  Layers,
  LayoutDashboard,
  LineChart,
  Lock,
  Mail,
  MessageSquare,
  Moon,
  Package,
  Pen,
  Plug,
  Radio,
  RefreshCw,
  Search,
  Server,
  Settings,
  Sun,
  User,
  Users,
  Wallet,
  Webhook,
  Wrench,
  X,
  Zap,
} from 'lucide-preact';

const REGISTRY = {
  'activity':         Activity,
  'alert-triangle':   AlertTriangle,
  'archive':          Archive,
  'banknote':         Banknote,
  'bar-chart-3':      BarChart3,
  'book-open':        BookOpen,
  'bot':              Bot,
  'brain':            Brain,
  'brain-circuit':    BrainCircuit,
  'chevron-down':     ChevronDown,
  'chevron-right':    ChevronRight,
  'clipboard-list':   ClipboardList,
  'clock':            Clock,
  'coins':            Coins,
  'cpu':              Cpu,
  'file-pen':         FilePen,
  'file-text':        FileText,
  'git-branch':       GitBranch,
  'globe':            Globe,
  'grid-3x3':         Grid3x3,
  'layers':           Layers,
  'layout-dashboard': LayoutDashboard,
  'line-chart':       LineChart,
  'lock':             Lock,
  'mail':             Mail,
  'message-square':   MessageSquare,
  'moon':             Moon,
  'package':          Package,
  'pen':              Pen,
  'plug':             Plug,
  'radio':            Radio,
  'refresh-cw':       RefreshCw,
  'search':           Search,
  'server':           Server,
  'settings':         Settings,
  'sun':              Sun,
  'user':             User,
  'users':            Users,
  'wallet':           Wallet,
  'webhook':          Webhook,
  'wrench':           Wrench,
  'x':                X,
  'zap':              Zap,
};

export default function Icon({ name, size = '1em', strokeWidth = 2, ...rest }) {
  if (!name) return null;
  const Comp = REGISTRY[String(name)];
  if (!Comp) {
    // Fallback: render the raw value (keeps compatibility with unknown names / emoji).
    return html`<span aria-hidden="true" ...${rest}>${name}</span>`;
  }
  return html`<${Comp} size=${size} strokeWidth=${strokeWidth} aria-hidden="true" ...${rest} />`;
}
